# Importing libraries and datasets


In [2]:
import pandas as pd
from google.colab import drive

drive.mount('/content/drive', force_remount = True)
directory = "/content/drive/MyDrive/Public_folder_Yahoo_RS/"

### Genres ###
genres_columns = ["Id", "Parent", "Level", "Name"]
genres = pd.read_csv(directory + "genre-hierarchy.txt", header = None, sep = '\t', names = genres_columns)
### Songs ###
songs_columns = ["Id", "Album", "Artist", "Genre"]
songs = pd.read_csv(directory + "song-attributes.txt", header = None, sep = '\t', names = songs_columns)
### Ratings ###
ratings_columns = ["User", "Song", "Rating"]
ratings = pd.read_csv(directory + "train_0.txt", header = None, sep = '\t', names = ratings_columns)
print(ratings)

Mounted at /content/drive
            User    Song  Rating
0              0     166       5
1              0    2245       4
2              0    3637       4
3              0    5580       4
4              0    5859       4
...          ...     ...     ...
76344622  199999  131247       5
76344623  199999  132979       5
76344624  199999  133678       5
76344625  199999  134265       1
76344626  199999  135121       1

[76344627 rows x 3 columns]


# Analyzing the users and finding the ones with the most ratings

In [3]:
users_num_ratings = []
cnt = 0

for i in range(int(len(ratings['User']) / 30)): 
    if(ratings['User'][i] == ratings['User'][i + 1]):
        cnt += 1
    else:
        users_num_ratings.append([ratings['User'][i], cnt + 1])
        cnt = 0

print("Total users analyzed : " + str(len(users_num_ratings)))
users_num_ratings.sort(key = lambda x: x[1], reverse = True)
users_num_ratings = users_num_ratings[0:1000]
users_num_ratings.sort(key = lambda x: x[0], reverse = True)
print(users_num_ratings)
participant_users = []
for user in users_num_ratings:
    participant_users.append(user[0])
print(participant_users)

Total users analyzed : 6730
[[6727, 660], [6711, 844], [6706, 716], [6703, 4487], [6700, 1048], [6694, 5662], [6688, 5033], [6686, 1150], [6674, 994], [6661, 1181], [6658, 1638], [6655, 1309], [6642, 3701], [6641, 1150], [6633, 915], [6631, 806], [6629, 803], [6627, 644], [6625, 658], [6602, 1480], [6595, 1746], [6592, 1393], [6588, 723], [6585, 658], [6584, 2508], [6578, 1412], [6571, 1500], [6568, 1469], [6564, 1169], [6545, 6233], [6544, 2627], [6540, 856], [6532, 1196], [6523, 2130], [6522, 3853], [6515, 3457], [6511, 718], [6501, 1091], [6498, 2835], [6496, 2168], [6493, 1336], [6484, 1225], [6482, 3971], [6467, 839], [6466, 840], [6464, 5940], [6463, 2471], [6451, 687], [6433, 1080], [6432, 937], [6430, 2397], [6426, 1076], [6419, 4775], [6416, 1087], [6392, 2479], [6391, 695], [6379, 989], [6371, 752], [6363, 3192], [6358, 2136], [6357, 1040], [6349, 1769], [6347, 1047], [6337, 677], [6334, 5861], [6323, 2266], [6320, 1895], [6317, 1007], [6311, 877], [6310, 1151], [6307, 895], 

# Filtering the ratings and keeping only the useful ones

In [4]:
import numpy as np

np_ratings = np.array(ratings)

useful_ratings = []
max_limit = max(participant_users)
index = 0
current = participant_users.pop()
while(np_ratings[index][0] < max_limit + 1):
    if(np_ratings[index][0] == current):
        useful_ratings.append(np_ratings[index])
    if(np_ratings[index][0] > current):
        if(participant_users != []):
            current = participant_users.pop()
        else:
            break
    index = index + 1

np_useful_ratings = np.array(useful_ratings)
print(np_useful_ratings)

[[     6     67      1]
 [     6     69      1]
 [     6    137      5]
 ...
 [  6727 136479      1]
 [  6727 136649      2]
 [  6727 136713      3]]


# Verifing the number of users we work with

In [5]:
users_num_ratings = []
cnt = 0

for j in range(len(np_useful_ratings)):
    if(j == len(np_useful_ratings) - 1):
        users_num_ratings.append([np_useful_ratings[j][0], cnt + 1])
    else:
        if(np_useful_ratings[j][0] == np_useful_ratings[j + 1][0]):
            cnt += 1
        else:
            users_num_ratings.append([np_useful_ratings[j][0], cnt + 1])
            cnt = 0

print("Total users analyzed : " + str(len(users_num_ratings)))
print(users_num_ratings)
participant_users = []
for user in users_num_ratings:
    participant_users.append(user[0])
print(participant_users)

Total users analyzed : 1000
[[6, 1349], [12, 705], [20, 1365], [21, 3243], [23, 3188], [25, 2764], [26, 857], [36, 642], [38, 650], [61, 1306], [75, 1017], [82, 916], [91, 2423], [94, 651], [95, 1755], [98, 1087], [100, 2087], [102, 6311], [106, 8369], [116, 939], [118, 703], [121, 1471], [126, 790], [132, 769], [138, 2310], [141, 962], [146, 11778], [150, 1442], [157, 647], [165, 1602], [175, 3106], [202, 739], [203, 1268], [207, 1697], [211, 1503], [215, 1652], [226, 939], [229, 822], [233, 919], [238, 1050], [239, 2250], [243, 933], [263, 4580], [275, 663], [276, 3884], [284, 1509], [302, 1842], [306, 736], [312, 2223], [313, 989], [325, 1172], [333, 1133], [340, 1009], [343, 1244], [359, 1166], [360, 1882], [367, 932], [373, 2212], [379, 827], [382, 1738], [393, 1248], [398, 683], [399, 2225], [421, 1430], [423, 1499], [424, 2204], [432, 725], [436, 1268], [437, 1336], [449, 831], [452, 3099], [455, 790], [468, 4290], [490, 833], [493, 1397], [497, 860], [498, 813], [500, 686], [50

# Getting informed about the songs that correspond to the users

In [6]:
total_songs = []
for rating in np_useful_ratings:
    total_songs.append(rating[1])
np_total_songs = np.array(total_songs)
np_total_songs.sort()
np_total_songs = np.unique(np_total_songs)
print(len(np_total_songs))

134596


# Initializing the matrix

In [7]:
matrix = np.zeros((len(participant_users), len(np_total_songs)), dtype = np.ushort)

df_matrix = pd.DataFrame(matrix, columns = np_total_songs, index = participant_users)
df_matrix

0       1       2       3       4       5       6       7       8       \
6          0       0       0       0       0       0       0       0       0   
12         0       0       0       0       0       0       0       0       0   
20         0       0       0       0       0       0       0       0       0   
21         0       0       0       0       0       0       0       0       0   
23         0       0       0       0       0       0       0       0       0   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
6700       0       0       0       0       0       0       0       0       0   
6703       0       0       0       0       0       0       0       0       0   
6706       0       0       0       0       0       0       0       0       0   
6711       0       0       0       0       0       0       0       0       0   
6727       0       0       0       0       0       0       0       0       0   

      9       ...  136726  136727  136728  136729  136730  136731  136732  \
6          0  ...       0       0       0       0       0       0       0   
12         0  ...       0       0       0       0       0       0       0   
20         0  ...       0       0       0       0       0       0       0   
21         0  ...       0       0       0       0       0       0       0   
23         0  ...       0       0       0       0       0       0       0   
...      ...  ...     ...     ...     ...     ...     ...     ...     ...   
6700       0  ...       0       0       0       0       0       0       0   
6703       0  ...       0       0       0       0       0       0       0   
6706       0  ...       0       0       0       0       0       0       0   
6711       0  ...       0       0       0       0       0       0       0   
6727       0  ...       0       0       0       0       0       0       0   

      136733  136734  136735  
6          0       0       0  
12         0       0       0  
20         0       0       0  
21         0       0       0  
23         0       0       0  
...      ...     ...     ...  
6700       0       0       0  
6703       0       0       0  
6706       0       0       0  
6711       0       0       0  
6727       0       0       0  

[1000 rows x 134596 columns]

# Filling the matrix with the ratings

In [8]:
for rating in np_useful_ratings:
    df_matrix.loc[rating[0]][rating[1]] = rating[2]

df_matrix

0       1       2       3       4       5       6       7       8       \
6          0       0       0       0       0       0       0       0       0   
12         0       0       0       0       0       0       0       0       0   
20         0       0       0       0       0       0       0       0       0   
21         0       0       0       0       0       0       0       0       0   
23         0       0       0       0       0       0       0       0       0   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
6700       0       0       0       0       0       0       0       0       0   
6703       0       0       0       0       0       0       0       0       0   
6706       0       0       0       0       0       0       0       0       0   
6711       0       0       0       0       0       0       0       0       0   
6727       0       0       0       0       0       0       0       0       0   

      9       ...  136726  136727  136728  136729  136730  136731  136732  \
6          0  ...       0       0       0       0       0       0       0   
12         0  ...       0       0       0       0       0       0       0   
20         0  ...       0       0       0       0       0       0       0   
21         0  ...       0       0       0       0       0       0       0   
23         0  ...       0       0       0       0       0       0       0   
...      ...  ...     ...     ...     ...     ...     ...     ...     ...   
6700       0  ...       0       0       0       0       0       0       0   
6703       0  ...       0       0       0       0       0       0       0   
6706       0  ...       0       0       0       0       0       0       0   
6711       0  ...       0       0       0       0       0       0       0   
6727       0  ...       0       0       0       0       0       0       0   

      136733  136734  136735  
6          0       0       0  
12         0       0       0  
20         0       0       0  
21         0       0       0  
23         0       0       0  
...      ...     ...     ...  
6700       0       0       0  
6703       0       0       0  
6706       0       0       0  
6711       0       0       0  
6727       0       0       0  

[1000 rows x 134596 columns]

In [9]:
df_matrix.loc[6727][136649]

2

# Preprocessing the genre and the song table

In [10]:
### Finding the root of each genre ###
np_genres = np.array(genres)
roots = []
for genre in np_genres:
    current = genre[0]
    parent = genre[1]
    while(current != parent):
        current = parent
        parent = np_genres[current][1]
    roots.append(current)
print("Genre with id = 8 : " + str(np_genres[7][3]))
print("The root of this genre is : " + str(np_genres[roots[7]][3]))

Genre with id = 8 : House
The root of this genre is : Electronic/Dance


In [11]:
### Replacing the genre of every song with the root of the genre ###
np_songs = np.array(songs)
for song in range(len(np_songs)):
    np_songs[song][3] = roots[np_songs[song][3]]

# Computing the mean(ratings) by user and genre

In [12]:
### These two dictionaries will help us compute the mean(rating) of every user, depending on the genre of the song ###
### ratings_sum_by_genre : {'i-j': a} means that the user i has total sum(rating) = a in genre j ###
### ratings_by_genre : {'i-j': a} means that the user i has rated a songs with genre j ###
ratings_sum_by_genre = {}
ratings_by_genre = {}
for user in participant_users:
    for genre in np.sort(np.unique(np.array(roots))):
        ratings_sum_by_genre[str(user) + "-" + str(genre)] = 0
        ratings_by_genre[str(user) + "-" + str(genre)] = 0

participant_users.reverse()
max_limit = max(participant_users)
index = 0
current = participant_users.pop()
while(np_ratings[index][0] < max_limit + 1):
    if(np_ratings[index][0] == current):
        ratings_sum_by_genre[str(np_ratings[index][0]) + "-" + str(np_songs[np_ratings[index][1]][3])] += np.ushort(np_ratings[index][2])
        ratings_by_genre[str(np_ratings[index][0]) + "-" + str(np_songs[np_ratings[index][1]][3])] += 1
    if(np_ratings[index][0] > current):
        if(participant_users != []):
            current = participant_users.pop()
        else:
            break
    index = index + 1

### Finally the division (ratings_sum_by_genre / ratings_by_genre) will give us the mean(rating) by user and genre ###
for rating in ratings_sum_by_genre:
    if(ratings_by_genre[rating] != 0):
        ratings_sum_by_genre[rating] /= ratings_by_genre[rating]

In [13]:
print("The user with id = 6 has mean(rating) = " + str(ratings_sum_by_genre['6-0']) + " in genre with id = 0")

The user with id = 6 has mean(rating) = 3.109016393442623 in genre with id = 0


In [14]:
participant_users = []
for user in users_num_ratings:
    participant_users.append(user[0])
print(participant_users)

[6, 12, 20, 21, 23, 25, 26, 36, 38, 61, 75, 82, 91, 94, 95, 98, 100, 102, 106, 116, 118, 121, 126, 132, 138, 141, 146, 150, 157, 165, 175, 202, 203, 207, 211, 215, 226, 229, 233, 238, 239, 243, 263, 275, 276, 284, 302, 306, 312, 313, 325, 333, 340, 343, 359, 360, 367, 373, 379, 382, 393, 398, 399, 421, 423, 424, 432, 436, 437, 449, 452, 455, 468, 490, 493, 497, 498, 500, 505, 507, 510, 527, 532, 539, 542, 546, 551, 552, 563, 567, 568, 574, 588, 592, 593, 597, 603, 604, 605, 626, 629, 639, 642, 644, 646, 654, 655, 660, 680, 687, 699, 702, 708, 715, 719, 720, 734, 736, 741, 744, 750, 773, 776, 783, 793, 802, 816, 838, 853, 861, 869, 870, 871, 882, 885, 888, 894, 910, 911, 912, 915, 921, 922, 933, 937, 946, 968, 975, 997, 1004, 1011, 1017, 1032, 1045, 1049, 1051, 1064, 1066, 1088, 1091, 1092, 1097, 1099, 1103, 1113, 1117, 1119, 1121, 1133, 1141, 1143, 1145, 1152, 1176, 1190, 1207, 1209, 1210, 1212, 1213, 1214, 1217, 1226, 1233, 1234, 1237, 1242, 1243, 1244, 1255, 1266, 1280, 1304, 1319, 1

# Detecting the zeros' percentage of the matrix

In [15]:
np_matrix = np.array(df_matrix)

print(np_matrix)
total_cells = len(participant_users) * len(np_total_songs)
print("Total cells: " + str(total_cells))
non_zero_cells = np.count_nonzero(np_matrix)
print("Total non zeros: " + str(non_zero_cells))
print("Positive percentage: " + str(non_zero_cells / total_cells))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Total cells: 134596000
Total non zeros: 1633889
Positive percentage: 0.012139209188980355


# Replacing the zeros of the matrix with the mean(ratings) by user and genre

In [16]:
users_dictionary = {}
for j in range(len(participant_users)):
    users_dictionary[j] = participant_users[j]

songs_dictionary = {}
for j in range(len(np_total_songs)):
    songs_dictionary[j] = np_total_songs[j]

for user in range(len(participant_users)):
    for song in range(len(np_total_songs)):
        if(np_matrix[user][song] == 0):
            np_matrix[user][song] = ratings_sum_by_genre[str(users_dictionary[user]) + "-" + str(np_songs[songs_dictionary[song]][3])]

df_matrix = pd.DataFrame(np_matrix, columns = np_total_songs, index = participant_users)
df_matrix

0       1       2       3       4       5       6       7       8       \
6          3       3       3       3       3       3       2       3       3   
12         3       3       3       3       3       3       0       0       3   
20         2       1       2       2       2       2       1       1       2   
21         1       1       1       1       1       1       1       1       1   
23         3       3       3       3       3       3       3       4       3   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
6700       2       2       2       2       2       2       3       3       2   
6703       3       3       3       3       3       3       2       2       3   
6706       3       3       3       3       3       3       3       1       3   
6711       1       1       1       1       1       1       1       1       1   
6727       3       3       3       3       3       3       1       0       3   

      9       ...  136726  136727  136728  136729  136730  136731  136732  \
6          0  ...       3       3       3       3       3       3       3   
12         0  ...       3       3       3       3       3       3       3   
20         1  ...       2       2       2       2       2       2       2   
21         1  ...       1       1       1       1       1       1       1   
23         4  ...       3       3       3       3       3       3       3   
...      ...  ...     ...     ...     ...     ...     ...     ...     ...   
6700       0  ...       2       2       2       2       2       2       2   
6703       3  ...       3       3       3       3       3       3       3   
6706       0  ...       3       3       3       3       3       3       3   
6711       1  ...       1       1       1       1       1       1       1   
6727       0  ...       3       3       3       3       3       3       3   

      136733  136734  136735  
6          3       3       3  
12         3       3       3  
20         2       2       2  
21         1       1       1  
23         3       3       3  
...      ...     ...     ...  
6700       2       2       2  
6703       3       3       3  
6706       3       3       3  
6711       1       1       1  
6727       3       3       3  

[1000 rows x 134596 columns]

# Detecting again the zeros' percentage of the matrix

In [17]:
print(np_matrix)
total_cells = len(participant_users) * len(np_total_songs)
print("Total cells: " + str(total_cells))
non_zero_cells = np.count_nonzero(np_matrix)
print("Total non zeros: " + str(non_zero_cells))
print("Positive percentage: " + str(non_zero_cells / total_cells))

[[3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 [2 1 2 ... 2 2 2]
 ...
 [3 3 3 ... 3 3 3]
 [1 1 1 ... 1 1 1]
 [3 3 3 ... 3 3 3]]
Total cells: 134596000
Total non zeros: 131473616
Positive percentage: 0.9768018068887634


# Completing the rest gaps of the matrix with the mean(ratings) by user only

In [18]:
for user in np_matrix:
    m = np.mean(user[user > 0])
    user[user == 0] = m

print(np_matrix)
total_cells = len(participant_users) * len(np_total_songs)
print("Total cells: " + str(total_cells))
non_zero_cells = np.count_nonzero(np_matrix)
print("Total non zeros: " + str(non_zero_cells))
print("Positive percentage: " + str(non_zero_cells / total_cells))

[[3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 [2 1 2 ... 2 2 2]
 ...
 [3 3 3 ... 3 3 3]
 [1 1 1 ... 1 1 1]
 [3 3 3 ... 3 3 3]]
Total cells: 134596000
Total non zeros: 134596000
Positive percentage: 1.0


# Presenting the final matrix

In [19]:
df_matrix = pd.DataFrame(np_matrix, columns = np_total_songs, index = participant_users)
df_matrix

0       1       2       3       4       5       6       7       8       \
6          3       3       3       3       3       3       2       3       3   
12         3       3       3       3       3       3       3       3       3   
20         2       1       2       2       2       2       1       1       2   
21         1       1       1       1       1       1       1       1       1   
23         3       3       3       3       3       3       3       4       3   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
6700       2       2       2       2       2       2       3       3       2   
6703       3       3       3       3       3       3       2       2       3   
6706       3       3       3       3       3       3       3       1       3   
6711       1       1       1       1       1       1       1       1       1   
6727       3       3       3       3       3       3       1       2       3   

      9       ...  136726  136727  136728  136729  136730  136731  136732  \
6          2  ...       3       3       3       3       3       3       3   
12         3  ...       3       3       3       3       3       3       3   
20         1  ...       2       2       2       2       2       2       2   
21         1  ...       1       1       1       1       1       1       1   
23         4  ...       3       3       3       3       3       3       3   
...      ...  ...     ...     ...     ...     ...     ...     ...     ...   
6700       2  ...       2       2       2       2       2       2       2   
6703       3  ...       3       3       3       3       3       3       3   
6706       2  ...       3       3       3       3       3       3       3   
6711       1  ...       1       1       1       1       1       1       1   
6727       2  ...       3       3       3       3       3       3       3   

      136733  136734  136735  
6          3       3       3  
12         3       3       3  
20         2       2       2  
21         1       1       1  
23         3       3       3  
...      ...     ...     ...  
6700       2       2       2  
6703       3       3       3  
6706       3       3       3  
6711       1       1       1  
6727       3       3       3  

[1000 rows x 134596 columns]

# Applying the SVD transformation

In [20]:
KapaParameter = 100   
U, S, VT = np.linalg.svd(np_matrix, full_matrices = False)
U = U[:, :KapaParameter]
S = S[:KapaParameter]
V = VT[:KapaParameter, :].T

# Printing the shapes of the new matrices

In [21]:
print("Initial matrix :" + str(matrix.shape[0]) + "x" + str(matrix.shape[1]))
print("Users vector U :" + str(U.shape[0]) + "x" + str(U.shape[1]))
print("Sigma matrix Σ :" + str(S.shape[0]) + "x" + str(S.shape[0]))
print("Songs vector V :" + str(V.shape[0]) + "x" + str(V.shape[1]))

Initial matrix :1000x134596
Users vector U :1000x100
Sigma matrix Σ :100x100
Songs vector V :134596x100


# Presenting the U : users' vectors

In [22]:
df_U = pd.DataFrame(U, columns = range(KapaParameter), index = participant_users)
df_U

0         1         2         3         4         5         6   \
6    -0.033690  0.000427  0.021468  0.036438 -0.036203  0.008908 -0.036985   
12   -0.034163  0.012788 -0.009889  0.006710  0.005809  0.006151  0.008362   
20   -0.021442 -0.044934  0.021217 -0.000832 -0.002788 -0.007359 -0.003477   
21   -0.011759  0.008691 -0.010487  0.017889  0.017176  0.088366  0.048320   
23   -0.034569  0.019445 -0.031179  0.040117  0.015717 -0.026333 -0.038824   
...        ...       ...       ...       ...       ...       ...       ...   
6700 -0.023280  0.019873 -0.049450 -0.006712 -0.019423 -0.009731 -0.002101   
6703 -0.033424 -0.004883  0.044986 -0.000681  0.012817 -0.070775 -0.035830   
6706 -0.033630  0.000826  0.038137 -0.063380  0.008276  0.045899 -0.011805   
6711 -0.011403  0.004214 -0.003418  0.002214  0.002149  0.001773  0.003222   
6727 -0.033187 -0.011596  0.067841  0.040767 -0.016615 -0.014599 -0.009508   

            7         8         9   ...        90        91        92  \
6     0.011444 -0.008196  0.035137  ... -0.023294 -0.023272  0.005358   
12   -0.002700  0.004455  0.002438  ... -0.001642  0.002510  0.000068   
20   -0.003774 -0.004699 -0.001434  ...  0.034183 -0.032879 -0.022654   
21    0.075421  0.014886 -0.011329  ...  0.001705  0.036969  0.014596   
23    0.056236 -0.070073  0.001389  ...  0.017100  0.009222 -0.015036   
...        ...       ...       ...  ...       ...       ...       ...   
6700  0.005811 -0.009831  0.010020  ...  0.020700  0.016628 -0.017724   
6703  0.047123 -0.029651 -0.032799  ... -0.016033  0.014939 -0.002348   
6706 -0.029377 -0.042518 -0.054439  ... -0.006014 -0.006253 -0.004332   
6711 -0.001000  0.001342  0.001478  ... -0.001380 -0.003449 -0.007087   
6727  0.001505  0.003635  0.005177  ... -0.012826  0.001836  0.005776   

            93        94        95        96        97        98        99  
6    -0.005152  0.009253 -0.007615  0.006131 -0.003503  0.004758 -0.016539  
12   -0.002856  0.004280 -0.003392  0.007065 -0.002927 -0.007779 -0.000643  
20   -0.033251 -0.018026 -0.089006 -0.019642 -0.045920  0.039043  0.078398  
21   -0.002827 -0.041784  0.073313 -0.012666  0.010844 -0.067417 -0.091068  
23   -0.016725  0.012003  0.010953 -0.026340 -0.005662 -0.027883 -0.002043  
...        ...       ...       ...       ...       ...       ...       ...  
6700  0.010748 -0.036308  0.000684  0.006179  0.021692 -0.030176 -0.029357  
6703  0.000293  0.011574 -0.029144 -0.011918  0.001790 -0.014816 -0.009063  
6706 -0.002316  0.005214 -0.010636 -0.004195  0.013274  0.002134 -0.004718  
6711  0.003532  0.000170 -0.005569  0.007623 -0.003173 -0.008647 -0.007286  
6727 -0.004066  0.017298  0.011357 -0.002469 -0.000573  0.002459 -0.004896  

[1000 rows x 100 columns]

# Presenting the V : songs' vectors

In [23]:
df_V = pd.DataFrame(V, columns = range(KapaParameter), index = np_total_songs)
df_V

0         1         2         3         4         5         6   \
0      -0.002756 -0.001000  0.000393  0.000047 -0.000134 -0.000056  0.000098   
1      -0.002563  0.009315  0.004630  0.000006 -0.001580 -0.000856 -0.000715   
2      -0.002749 -0.000890  0.000318 -0.000110 -0.000082  0.000010 -0.000034   
3      -0.002749 -0.000966  0.000298  0.000153 -0.000022 -0.000120  0.000028   
4      -0.002750 -0.000941  0.000295 -0.000190 -0.000031 -0.000056  0.000063   
...          ...       ...       ...       ...       ...       ...       ...   
136731 -0.002753 -0.000951  0.000258 -0.000103 -0.000287 -0.000265  0.000008   
136732 -0.002758 -0.000897  0.000264 -0.000026 -0.000041  0.000041  0.000322   
136733 -0.002756 -0.000910  0.000464 -0.000089 -0.000144 -0.000044  0.000513   
136734 -0.002747 -0.001015  0.000284 -0.000112 -0.000173  0.000082  0.000459   
136735 -0.002764 -0.001197  0.000174  0.000116 -0.000270  0.000215 -0.000737   

              7         8         9   ...        90        91        92  \
0       0.000170 -0.000111 -0.000093  ...  0.001008 -0.000425  0.000213   
1       0.000290 -0.000030  0.000016  ... -0.000038  0.000613  0.000154   
2       0.000157 -0.000007 -0.000003  ...  0.000262 -0.001557 -0.002908   
3      -0.000052 -0.000202 -0.000054  ...  0.000455 -0.000860 -0.001724   
4      -0.000040 -0.000012 -0.000061  ... -0.000281  0.000359 -0.000230   
...          ...       ...       ...  ...       ...       ...       ...   
136731  0.000191 -0.000222 -0.000218  ... -0.000584 -0.000608 -0.000588   
136732 -0.000541 -0.000789 -0.000091  ...  0.001821 -0.000871 -0.000576   
136733 -0.000422 -0.000138  0.000144  ... -0.003227 -0.002490  0.000244   
136734 -0.000145  0.000179  0.000060  ...  0.000016  0.000237  0.000098   
136735 -0.000546  0.000196 -0.000093  ... -0.003027  0.000447  0.001217   

              93        94        95        96        97        98        99  
0       0.004660  0.002804 -0.002866 -0.000744 -0.006417  0.000932  0.000830  
1       0.000961 -0.000297  0.001658  0.000155 -0.000407 -0.000063 -0.001041  
2      -0.000804 -0.000202  0.000966  0.001015  0.000899  0.000051  0.000412  
3       0.001177 -0.001749  0.000525  0.000371  0.000829 -0.002153 -0.000409  
4       0.000710 -0.000220  0.000477 -0.000315  0.000061 -0.000303 -0.000283  
...          ...       ...       ...       ...       ...       ...       ...  
136731 -0.000640  0.000220 -0.001841  0.000685 -0.000267 -0.001669 -0.001840  
136732 -0.001606 -0.000253  0.000862 -0.000068 -0.001034  0.000667 -0.002139  
136733 -0.001910  0.000570  0.003706  0.008664 -0.002833 -0.003912  0.004944  
136734  0.000392  0.000464 -0.000082  0.000060  0.000092 -0.000058 -0.000023  
136735  0.002577  0.003442 -0.002524  0.001886  0.001785 -0.004002 -0.000141  

[134596 rows x 100 columns]

# Computing similarities between users

In [24]:
from scipy import spatial

total_similarities = []
for user0 in range(len(participant_users)):
    similarities = []
    for user1 in range(len(participant_users)): 
        similarities.append(1 - spatial.distance.cosine(U[user0], U[user1]))
    total_similarities.append(similarities)

np_total_similarities = np.array(total_similarities)
print(np_total_similarities[0][10])

0.011493128802706254


In [25]:
df_similarities = pd.DataFrame(np_total_similarities, columns = participant_users, index = participant_users)
df_similarities

6         12        20        21        23        25        26    \
6     1.000000  0.041283 -0.109641 -0.005479  0.134638  0.013905 -0.288041   
12    0.041283  1.000000 -0.045594 -0.064607  0.141675 -0.062567  0.116454   
20   -0.109641 -0.045594  1.000000 -0.072118 -0.090328  0.071299  0.283927   
21   -0.005479 -0.064607 -0.072118  1.000000 -0.090455 -0.060302  0.051513   
23    0.134638  0.141675 -0.090328 -0.090455  1.000000 -0.019869 -0.282682   
...        ...       ...       ...       ...       ...       ...       ...   
6700 -0.177948 -0.327544 -0.122723  0.006433  0.171397 -0.017796  0.118960   
6703 -0.023256 -0.003084  0.001618 -0.000712 -0.041953 -0.009994  0.030686   
6706  0.019749  0.109813 -0.022942 -0.016309 -0.180952  0.037393 -0.108141   
6711  0.047738  0.183326 -0.088912  0.000870 -0.085167 -0.112437 -0.047195   
6727  0.432721 -0.022995 -0.038691 -0.037970  0.127854  0.083960 -0.227437   

          36        38        61    ...      6661      6674      6686  \
6    -0.064205  0.000292  0.112517  ... -0.154943 -0.167029  0.262236   
12    0.325387  0.020332 -0.076212  ...  0.408124  0.104620  0.148797   
20   -0.276288 -0.171652 -0.017128  ... -0.020253 -0.017362 -0.104879   
21   -0.027020 -0.020724  0.013207  ... -0.020033 -0.054146 -0.020232   
23    0.037435  0.230700 -0.276422  ...  0.189495 -0.111444  0.095118   
...        ...       ...       ...  ...       ...       ...       ...   
6700  0.063744  0.342500  0.075966  ...  0.009958  0.258511 -0.078251   
6703 -0.010851 -0.009896  0.000352  ...  0.079945  0.006882 -0.009254   
6706  0.271788 -0.174070  0.314466  ...  0.133788  0.097738 -0.304048   
6711  0.177729  0.184813 -0.071062  ...  0.162719  0.116427 -0.032930   
6727 -0.032475 -0.223811  0.106604  ... -0.339772 -0.122644  0.400518   

          6688      6694      6700      6703      6706      6711      6727  
6     0.038758 -0.070275 -0.177948 -0.023256  0.019749  0.047738  0.432721  
12   -0.137097  0.009144 -0.327544 -0.003084  0.109813  0.183326 -0.022995  
20    0.392976  0.021637 -0.122723  0.001618 -0.022942 -0.088912 -0.038691  
21   -0.014102 -0.018918  0.006433 -0.000712 -0.016309  0.000870 -0.037970  
23   -0.105642  0.043449  0.171397 -0.041953 -0.180952 -0.085167  0.127854  
...        ...       ...       ...       ...       ...       ...       ...  
6700  0.026251 -0.046044  1.000000 -0.026596 -0.104327 -0.021086 -0.015695  
6703  0.002091 -0.001894 -0.026596  1.000000 -0.006035 -0.017719  0.024599  
6706 -0.012569 -0.034234 -0.104327 -0.006035  1.000000  0.023059 -0.007826  
6711 -0.054606  0.055770 -0.021086 -0.017719  0.023059  1.000000  0.041693  
6727 -0.017681 -0.011988 -0.015695  0.024599 -0.007826  0.041693  1.000000  

[1000 rows x 1000 columns]

# Keeping only the useful ratings from the test set

In [26]:
ratings_columns = ["User", "Song", "Rating"]
test_ratings = pd.read_csv(directory + "test_0.txt", header = None, sep = '\t', names = ratings_columns)

np_test_ratings = np.array(test_ratings)
predicted_ratings = []

participant_users.reverse()
useful_test_ratings = []
max_limit = max(participant_users)
index = 0
current = participant_users.pop()
while(np_test_ratings[index][0] < max_limit + 1):
    if(np_test_ratings[index][0] == current):
        useful_test_ratings.append(np_test_ratings[index])
    if(np_test_ratings[index][0] > current):
        if(participant_users != []):
            current = participant_users.pop()
        else:
            break
    index = index + 1

np_useful_test_ratings = np.array(useful_test_ratings)
np_useful_test_ratings

array([[    6,  2323,     4],
       [    6, 18878,     4],
       [    6, 21675,     5],
       ...,
       [ 6727, 72989,     1],
       [ 6727, 74701,     3],
       [ 6727, 96788,     5]])

In [27]:
len(np_useful_test_ratings)

9850

In [28]:
participant_users = []
for user in users_num_ratings:
    participant_users.append(user[0])
print(participant_users)

[6, 12, 20, 21, 23, 25, 26, 36, 38, 61, 75, 82, 91, 94, 95, 98, 100, 102, 106, 116, 118, 121, 126, 132, 138, 141, 146, 150, 157, 165, 175, 202, 203, 207, 211, 215, 226, 229, 233, 238, 239, 243, 263, 275, 276, 284, 302, 306, 312, 313, 325, 333, 340, 343, 359, 360, 367, 373, 379, 382, 393, 398, 399, 421, 423, 424, 432, 436, 437, 449, 452, 455, 468, 490, 493, 497, 498, 500, 505, 507, 510, 527, 532, 539, 542, 546, 551, 552, 563, 567, 568, 574, 588, 592, 593, 597, 603, 604, 605, 626, 629, 639, 642, 644, 646, 654, 655, 660, 680, 687, 699, 702, 708, 715, 719, 720, 734, 736, 741, 744, 750, 773, 776, 783, 793, 802, 816, 838, 853, 861, 869, 870, 871, 882, 885, 888, 894, 910, 911, 912, 915, 921, 922, 933, 937, 946, 968, 975, 997, 1004, 1011, 1017, 1032, 1045, 1049, 1051, 1064, 1066, 1088, 1091, 1092, 1097, 1099, 1103, 1113, 1117, 1119, 1121, 1133, 1141, 1143, 1145, 1152, 1176, 1190, 1207, 1209, 1210, 1212, 1213, 1214, 1217, 1226, 1233, 1234, 1237, 1242, 1243, 1244, 1255, 1266, 1280, 1304, 1319, 1

# Defining the n most similar users for every user

In [29]:
n_closest = 5
total_similarar_users = []
for user0 in participant_users:
    similarities_list_with_index = []
    for user1 in participant_users:
        similarities_list_with_index.append([user1, df_similarities.loc[user0][user1]])
    similarities_list_with_index.sort(key = lambda x: x[1], reverse = True)
    similar_users = similarities_list_with_index[:n_closest]
    total_similarar_users.append(similar_users)

df_similar_users = pd.DataFrame(total_similarar_users, columns = range(n_closest), index = participant_users)
df_similar_users

0                            1                            2  \
6        [6, 1.0]   [1674, 0.5734213112110187]   [5493, 0.5695583743455058]   
12      [12, 1.0]    [490, 0.5802261306614038]   [5502, 0.5689117632433319]   
20      [20, 1.0]   [4116, 0.6348487210582318]   [1330, 0.6038606758135496]   
21      [21, 1.0]   [5462, 0.7107282271430373]   [5475, 0.6364166827107979]   
23      [23, 1.0]   [1416, 0.5345223328135751]  [4984, 0.48959185074109923]   
...           ...                          ...                          ...   
6700  [6700, 1.0]   [2127, 0.5488850289404351]   [5215, 0.5353373689832939]   
6703  [6703, 1.0]  [2863, 0.12169419911371737]  [1580, 0.10826734506232272]   
6706  [6706, 1.0]   [3715, 0.7754691744804211]   [2769, 0.7260497916803242]   
6711  [6711, 1.0]   [2641, 0.7631132319224219]   [5573, 0.7343923966916731]   
6727  [6727, 1.0]   [5104, 0.7699465639386388]   [4188, 0.6690379703925843]   

                                3                            4  
6      [3142, 0.5372545529962229]   [2478, 0.5205142581819141]  
12     [2702, 0.5660560953370171]   [4896, 0.5570899955053131]  
20     [4704, 0.5759149052783925]   [1449, 0.5077097435109688]  
21     [1411, 0.5995597787685512]   [5392, 0.5419397109194131]  
23     [3616, 0.4620997859976126]    [4497, 0.414681140902043]  
...                           ...                          ...  
6700   [2028, 0.5310154064630398]    [3851, 0.520243121116441]  
6703  [1623, 0.10652751669980642]  [6564, 0.08475751424782818]  
6706   [1207, 0.6587388869728743]   [1032, 0.6306756802936714]  
6711   [1145, 0.6673766045164993]   [5363, 0.6624117010035548]  
6727   [5804, 0.6362937337084146]   [5718, 0.6241466708813719]  

[1000 rows x 5 columns]

In [30]:
df_matrix

0       1       2       3       4       5       6       7       8       \
6          3       3       3       3       3       3       2       3       3   
12         3       3       3       3       3       3       3       3       3   
20         2       1       2       2       2       2       1       1       2   
21         1       1       1       1       1       1       1       1       1   
23         3       3       3       3       3       3       3       4       3   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
6700       2       2       2       2       2       2       3       3       2   
6703       3       3       3       3       3       3       2       2       3   
6706       3       3       3       3       3       3       3       1       3   
6711       1       1       1       1       1       1       1       1       1   
6727       3       3       3       3       3       3       1       2       3   

      9       ...  136726  136727  136728  136729  136730  136731  136732  \
6          2  ...       3       3       3       3       3       3       3   
12         3  ...       3       3       3       3       3       3       3   
20         1  ...       2       2       2       2       2       2       2   
21         1  ...       1       1       1       1       1       1       1   
23         4  ...       3       3       3       3       3       3       3   
...      ...  ...     ...     ...     ...     ...     ...     ...     ...   
6700       2  ...       2       2       2       2       2       2       2   
6703       3  ...       3       3       3       3       3       3       3   
6706       2  ...       3       3       3       3       3       3       3   
6711       1  ...       1       1       1       1       1       1       1   
6727       2  ...       3       3       3       3       3       3       3   

      136733  136734  136735  
6          3       3       3  
12         3       3       3  
20         2       2       2  
21         1       1       1  
23         3       3       3  
...      ...     ...     ...  
6700       2       2       2  
6703       3       3       3  
6706       3       3       3  
6711       1       1       1  
6727       3       3       3  

[1000 rows x 134596 columns]

# Predicting ratings based on the similarities and the matrix

In [31]:
predicted_ratings = []
for rating in np_useful_test_ratings:
    if rating[1] in np_total_songs:
        prediction = 0
        denominator = 0
        for similar_user in df_similar_users.loc[rating[0]]:
            prediction += df_matrix.loc[similar_user[0]][rating[1]] * similar_user[1]
            denominator += similar_user[1]
        predicted_ratings.append([rating[0], rating[1], prediction / denominator, rating[2]])

print(predicted_ratings)
print("Prediction : The user with id = " + str(predicted_ratings[0][0]) + " would rate with " + str(predicted_ratings[0][2]) + " the song with id = " + str(predicted_ratings[0][1] + 1) + ", while the actual rating is " + str(predicted_ratings[0][3]))

[[6, 2323, 2.832147213833165, 4], [6, 18878, 2.832147213833165, 4], [6, 21675, 3.0, 5], [6, 63178, 2.832147213833165, 3], [6, 78019, 2.832147213833165, 2], [6, 79425, 2.832147213833165, 5], [6, 79977, 2.832147213833165, 4], [6, 102020, 2.832147213833165, 5], [6, 104793, 2.832147213833165, 1], [6, 110674, 2.832147213833165, 5], [12, 10663, 3.520545352861664, 4], [12, 27328, 3.520545352861664, 5], [12, 42587, 3.520545352861664, 4], [12, 88523, 3.520545352861664, 5], [12, 89579, 3.520545352861664, 2], [12, 90889, 3.520545352861664, 5], [12, 101643, 3.0015903068061753, 4], [12, 102311, 3.520545352861664, 3], [12, 113766, 3.520545352861664, 4], [12, 121511, 3.520545352861664, 4], [20, 19670, 2.5890987299351766, 1], [20, 26328, 2.890091943217256, 1], [20, 45348, 2.54339898738368, 1], [20, 51936, 2.890091943217256, 1], [20, 57309, 2.890091943217256, 5], [20, 61662, 2.890091943217256, 5], [20, 68910, 3.081177099716592, 5], [20, 70014, 3.386811473944567, 5], [20, 80589, 2.5890987299351766, 1], 

# Computing the mean(ratings) by song

In [32]:
np_matrix_T = np_matrix.T
means_by_song = []

for j in range(len(np_matrix_T)):
    means_by_song.append(np.mean(np_matrix_T[j]))

means_by_song[0]

2.647

# Useful dictionaries : We need the transfers ***user_id*** <-> **matrix_row** and **song_id** <-> ***matrix_column***

In [33]:
users_dictionary_reversed = {}
for j in range(len(participant_users)):
    users_dictionary_reversed[participant_users[j]] = j

songs_dictionary_reversed = {}
for j in range(len(np_total_songs)):
    songs_dictionary_reversed[np_total_songs[j]] = j

# Giving the 50% of our prediction to the mean(ratings) by song

In [34]:
for rating in predicted_ratings:
    rating[2] = (rating[2] + means_by_song[songs_dictionary_reversed[rating[1]]]) / 2

print(predicted_ratings)
print("Prediction : The user with id = " + str(predicted_ratings[0][0]) + " would rate with " + str(predicted_ratings[0][2]) + " the song with id = " + str(predicted_ratings[0][1] + 1) + ", while the actual rating is " + str(predicted_ratings[0][3]))

[[6, 2323, 2.7410736069165824, 4], [6, 18878, 2.7060736069165827, 4], [6, 21675, 2.87, 5], [6, 63178, 2.7405736069165822, 3], [6, 78019, 2.7645736069165823, 2], [6, 79425, 2.7420736069165823, 5], [6, 79977, 2.7885736069165823, 4], [6, 102020, 2.7485736069165823, 5], [6, 104793, 2.7450736069165824, 1], [6, 110674, 2.8375736069165827, 5], [12, 10663, 3.082272676430832, 4], [12, 27328, 2.944272676430832, 5], [12, 42587, 3.092272676430832, 4], [12, 88523, 2.948772676430832, 5], [12, 89579, 3.099772676430832, 2], [12, 90889, 3.092272676430832, 5], [12, 101643, 2.8902951534030876, 4], [12, 102311, 3.0782726764308324, 3], [12, 113766, 3.0862726764308324, 4], [12, 121511, 3.088772676430832, 4], [20, 19670, 2.5585493649675883, 1], [20, 26328, 2.766545971608628, 1], [20, 45348, 2.58869949369184, 1], [20, 51936, 2.804545971608628, 1], [20, 57309, 2.768045971608628, 5], [20, 61662, 2.815545971608628, 5], [20, 68910, 2.867088549858296, 5], [20, 70014, 3.0414057369722833, 5], [20, 80589, 2.532549364

# Defining the mean squared error of our prediction

In [35]:
import math

total_error = 0
for prediction in predicted_ratings:
    total_error += (prediction[3] - prediction[2]) ** 2
mean_error = total_error / len(predicted_ratings)
print(mean_error)

2.27974005797865


# Showing the mean error if our predictions were totally random

In [36]:
random_predicted_ratings = []
for rating in np_useful_test_ratings:
    if rating[1] in np_total_songs:
        random_predicted_ratings.append([rating[0], rating[1], np.ushort(np.random.randint(0, 6)), rating[2]])

total_error = 0
for prediction in random_predicted_ratings:
    total_error += (prediction[3] - prediction[2]) ** 2
mean_error = total_error / len(random_predicted_ratings)
print(mean_error)

5.76102679026179


# Recommending songs for any user

In [37]:
user_id = int(input("Please insert the id of the user "))
while(user_id not in participant_users):
    user_id = int(input("Please insert a valid id for the user "))

predicted_ratings_for_user = []
for song in np_total_songs:
    prediction = 0
    for similar_user in df_similar_users.loc[user_id]:
        prediction += np_matrix[users_dictionary_reversed[similar_user[0]]][songs_dictionary_reversed[song]]
    predicted_ratings_for_user.append([song, prediction])
predicted_ratings_for_user.sort(key = lambda x: x[1], reverse = True)
recommendations = predicted_ratings_for_user[:5]
print("Recommendations for this user :")
count = 1
for song in recommendations:
    print(str(count) + ". " + str(song[0]))
    count = count + 1

Please insert the id of the user 42
Please insert a valid id for the user 7
Please insert a valid id for the user 6
Recommendations for this user :
1. 76654
2. 91987
3. 105189
4. 125956
5. 126757
